In [1]:
import pandas as pd

## Series

In [7]:
import numpy as np
arr = np.arange(100, 110)
print(arr)
# numpy는 왼쪽에서 오른쪾으로 배열됨

[100 101 102 103 104 105 106 107 108 109]


In [13]:
# numpy를 이용한 시리즈
arr = np.arange(100, 110)
s = pd.Series(arr)
print(s)
# 인덱스 번호와 값이 위에서 아래로 출력됨.

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [12]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [14]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series

In [16]:
# 데이터 타입이 섞여있으면 넓은 범위인 오브젝트롤 나옴
s = pd.Series([1, 2, 3, 4, 5, '99'])
print(s)

0     1
1     2
2     3
3     4
4     5
5    99
dtype: object


## indexing

In [19]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
s.index

RangeIndex(start=0, stop=4, step=1)

In [20]:
s[1]

'lee'

In [21]:
s[2]

'park'

In [23]:
# s[-1]
# pd.Series 는 음수 인덱싱 안됨.

In [27]:
s = pd.Series(person, index=['a', 'b', 'c', 'd'])
print(s)
# 인덱스 값을 주지 않은면 0123 이 출력되지만
# 인덱스 값을 주면 인덱스가 지정 됨.
# 인덱스 접근(딕셔너리 키 접근으로 생각하면 편함.)

a     kim
b     lee
c    park
d    hong
dtype: object


In [26]:
s['a']

'kim'

In [30]:
# 인덱스는 리스트도 가능
s = pd.Series(person, index = list('abcd'))
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [31]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [33]:
s.values
# numpy arrat 형태로 가져옴

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [35]:
s.ndim # 차원을 말해줌

1

In [36]:
s.shape

(4,)

### NaN(Not A Number)
- 결측치

In [39]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person + [np.nan])
print(s)
# 이 안에 데이터가 빠져있을떄 사용

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [42]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)
# float32를 사용하여 소수점 표현

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [43]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


In [48]:
s[['가', '다']]

가    바나나
다     사과
dtype: object

In [53]:
# s.iloc[[2, 3]] 똑같은 결과값
s[['다', '라']]

다    사과
라    포도
dtype: object

## bool

In [54]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [55]:
a = [[True, False, False, True, True]]
s[a]

KeyError: "None of [Index([(True, False, False, True, True)], dtype='object')] are in the [index]"

In [57]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [58]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [59]:
s[s <  10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [60]:
s[s == 5]

0    5
dtype: int64

## 결측치(NaN) 처리

In [63]:
s = pd.Series([2, 3, 2, 1, np.nan, 2, 4, 9, np.nan])
print(s)

0    2.0
1    3.0
2    2.0
3    1.0
4    NaN
5    2.0
6    4.0
7    9.0
8    NaN
dtype: float64


In [66]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [68]:
s[s.isnull()]
# isnull(): 결측치를 True 값으로 변환
# 이를 활용하여 True 값만 변환하는 s[] 를 활용하여 결측치를 찾을 수 있음

4   NaN
8   NaN
dtype: float64

In [71]:
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [73]:
s[s.notnull()]
# s.notnull() 은 결측치를 False로 만듬
# s[]는 True 값을 변환하기에 False를 뺌

0    2.0
1    3.0
2    2.0
3    1.0
5    2.0
6    4.0
7    9.0
dtype: float64

In [75]:
s[1:3]
# 슬라이싱은 글자도 가능함

1    3.0
2    2.0
dtype: float64

## DataFrame
- 시리즈의 확장이라고 생각하셈.

In [77]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:
df = pd.DataFrame(arr)
df
# 행과 열 표가 나옴

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [115]:
# 행과 열 이름지정
df = pd.DataFrame(arr, columns=['가', '나', '다'], index = ['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [116]:
# 딕셔너리 이름 지정하여 나옴
data = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul', 'LA', 'tokyo']
}
pd.DataFrame(data)

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [117]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [118]:
df.columns

Index(['가', '나', '다'], dtype='object')

In [119]:
df.values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
df.dtypes

가    int64
나    int64
다    int64
dtype: object

In [121]:
df.T

a  b  c
가  0  3  6
나  1  4  7
다  2  5  8

In [122]:
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

### colum

In [124]:
df = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul', 'LA', 'tokyo']
}
pd.DataFrame(df)

df['name']

['kim', 'lee', 'park']

In [126]:
type(df['name'])

list

In [127]:
df[['name', 'location']]

TypeError: unhashable type: 'list'

In [128]:
type(df[['name', 'location']])

TypeError: unhashable type: 'list'

In [132]:
# 컬럼 이름 바꾸기
# df.rename(columns={'location': 'hometown'})
# 위 식은 원본을 바꾸지 못함.
# 그래서 원본까지 수정하려면 덮어써야함.

df = df.rename(columns={'location': 'hometown'})

# 또는 df.rename(columns={'location': 'hometown'}, inplace=True)
# inplace=True 를 추가하여 저장할 수 있음

AttributeError: 'dict' object has no attribute 'rename'